server:
  port: 9000
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mateuszbuczek/remote-config-repository
          searchPaths:
          username: mateuszbuczek
          password: secret
management:
  server:
    port: 9001
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
