spring:
  servlet:
    multipart:
      enabled: true
#      Threshold after which files are written to disk.
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

app:
  file:
    upload-dir: /home/mateusz/webdev/tmp