spring:
  session:
    store-type: redis
    redis:
      namespace: spring:session
  redis:
    host: localhost
    port: 6379

management:
  health:
    redis:
      enabled: true

server:
  port: 8090
