spring:
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/postgres
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false

    show_sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
server:
  port: 0
logging:
  level:
    org:
      springframework:
        jdbc:
          core:
#            JdbcTemplate: DEBUG
            StatementCreatorUtils: TRACE

      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
    net:
      javacrumbs:
        shedlock: DEBUG