spring:
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/postgres
  flyway:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
