spring:
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    username: sa
    password: password
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
  quartz:
    job-store-type: jdbc
  h2:
    console:
      enabled: true

