spring:
  profiles:
    active: 'creds, local-db'
  r2dbc:
    url: r2dbc:pool:postgresql://${db.host}:${db.port}/${db.database}?currentSchema=${db.schema}
    username: ${db.username}
    password: ${db.password}
    pool:
      enabled: true
      max-size: 10
  # need to connect through jdbc
  flyway:
    url: jdbc:postgresql://${db.host}:${db.port}/${db.database}?currentSchema=${db.schema}
    user: ${db.username}
    password: ${db.password}

integration:
  payment-gateway:
    url: ${integration.payment-gateway.url}
    client-id: ${integration.payment-gateway.client-id}
    client-secret: ${integration.payment-gateway.client-secret}
    shop-id: ${integration.payment-gateway.shop-id}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
---
spring:
  config:
    activate:
      on-profile: local-db
db:
  host: localhost
  port: 5432
  database: postgres
  schema: test_schema
  username: user
  password: password
