# localstorage - mongo-pvc
# What do we want?
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  storageClassName: localstorage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
# How do we want it implemented
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-local-storage-pv
spec:
  storageClassName: localstorage
  capacity:
    storage: 12Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/some-directory/
    type: DirectoryOrCreate