kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: new-joiner
rules:
- apiGroups: ["", "apps", "extensions"] # Core API (v1) and apps (apps/v1)
  resources: ["*"]
  verbs: ["get", "list", "watch"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: put-specific-user-or-users-into-new-joiner-role
  namespace: default
subjects:
  # List users (defined in linux) that are going into this role
  - kind: User
    name: francis
roleRef:
  kind: Role
  name: new-joiner
  apiGroup: rbac.authorization.k8s.io/v1
---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: new-joiner
  namespace: playground
rules:
    - apiGroups: ["", "apps", "extensions"] # Core API (v1) and apps (apps/v1)
    resources: ["*"] # pods, services. NOT deployments
    verbs: ["*"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: playground-namespace-all
  namespace: playground
subjects:
  # List users (defined in linux) that are going into this role
  - kind: User
    name: francis
roleRef:
  kind: Role
  name: new-joiner
  apiGroup: rbac.authorization.k8s.io
