apiVersion: v1
kind: Service
metadata:
  #Unique key of the Service Instance
  name: fleetman-webapp
spec:
  # defines which pods are going to be represented
  # the service becomes a network endpoint for other services or external users
  selector:
    app: webapp

  ports:
    - name: http
      # expose
      port: 80
      # targetPort - optional
      # only for NodePort type >30 000
      nodePort: 30080

  # ClusterIP - expose port inside cluster
  # NodePort - expose port outside of cluster
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue
spec:
  selector:
    app: queue

  ports:
    - name: http
      port: 8161
      nodePort: 30010

    - name: endpoint
      port: 61616
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-position-tracker
spec:
  selector:
    app: position-tracker
  ports:
    - name: http
      port: 8080
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-api-gateway
spec:
  selector:
    app: api-gateway
  ports:
    - name: http
      port: 8080
  type: ClusterIP