apiVersion: v1
kind: Pod
metadata:
  name: sample-pod
spec:
  containers:
    - name: sample-pod
      image: alpine
      command: ["/bin/sh"]
      args: ["-c", "while true; do echo \"`date`\"; sleep 2; done"]

