server:
  port: ${PORT:0}
spring:
  application:
    name: rest-api
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

app:
  randomId: ${random.uuid}
