apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb-container
          image: mongo:3.6.5-jessie
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
      volumes:
        - name: mongo-persistent-storage
          # we can use whatever external storage for example Elastic Block Storage or locally in kubernetes cluster
#          hostPath:
#            path: /mnt/someDir
#            type: DirectoryOrCreate
          # we can also use pointer to the configuration (persistent volume claim)
          persistentVolumeClaim:
            claimName: mongo-pvc

---
kind: Service
apiVersion: v1
metadata:
  name: fleetman-mongodb
spec:
  selector:
    app: mongodb
  ports:
    - name: mongoport
      port: 27017
  type: ClusterIP