apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue
  namespace: default
spec:
  selector:
    matchLabels:
      app: queue
  replicas: 1
  template:
    metadata:
      labels:
        app: queue
    spec:
      containers:
        - name: queue-container
          image: richardchesterwood/k8s-fleetman-queue:release2
          resources:
            requests:
              # request in cluster node
              memory: 300Mi
              cpu: 100m
            limits:
              # if container exceed this it will be killed
              memory: 500Mi
              cpu: 200m

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: position-simulator
  namespace: default

spec:
  selector:
    matchLabels:
      app: position-simulator
  replicas: 1
  template:
    metadata:
      labels:
        app: position-simulator
    spec:
      containers:
        - name: position-simulator-container
          image: richardchesterwood/k8s-fleetman-position-simulator:release2
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: production-microservice

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: position-tracker
  namespace: default
spec:
  selector:
    matchLabels:
      app: position-tracker
  replicas: 1
  template:
    metadata:
      labels:
        app: position-tracker
    spec:
      containers:
        - name: position-tracker-container
          image: richardchesterwood/k8s-fleetman-position-tracker:release3
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: production-microservice

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: default
spec:
  selector:
    matchLabels:
      app: api-gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway-container
          image: richardchesterwood/k8s-fleetman-api-gateway:release2
          readinessProbe:
            httpGet:
              path: /
              port: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: production-microservice

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: default
spec:
  selector:
    matchLabels:
      app: webapp
  replicas: 1
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp-container
          image: richardchesterwood/k8s-fleetman-webapp-angular:release2
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: production-microservice